branch-defaults:
  default:
    environment: babyhallo-test
global:
  application_name: babyhallo
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2015.09 v2.0.4 running PHP 5.6
  default_region: eu-central-1
  profile: eb-cli
  sc: null
